/*
Name: Noah Carmichael
Description: The startup and login screen for the computer simulator. Username is "username" (non case dependant), password is "password" (case dependant).
Opens main.java on succesful login
 */
package com.mycompany.fpt;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import static java.lang.System.out;
import javax.swing.ImageIcon;
import javax.swing.Timer;


public class Start extends javax.swing.JFrame {

    public Start() {
        initComponents();
        power.setVisible(false);
        hideLogoAfterDelay();
        setLocation(50, 50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        Enter = new javax.swing.JButton();
        background = new javax.swing.JPanel();
        power = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/bindows.jpg"))); // NOI18N
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logo.setOpaque(true);
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 750, 300));

        usernameInput.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });
        getContentPane().add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 120, -1));

        Username.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username.setText("Username");
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 800, -1));

        Password.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Password.setText("Password");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 800, -1));

        Title.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Macrohard Bindows 10.5");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 800, 50));

        passwordInput.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        getContentPane().add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 120, -1));

        Enter.setFont(new java.awt.Font("Futura Md BT", 0, 14)); // NOI18N
        Enter.setText("Login");
        Enter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });
        getContentPane().add(Enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 80, 30));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        power.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/power.png"))); // NOI18N
        power.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        power.setContentAreaFilled(false);
        power.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerActionPerformed(evt);
            }
        });
        background.add(power, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 60, 60));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputActionPerformed

    
    // enter button
    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed
        String enteredUsername = usernameInput.getText();
        char[] enteredPasswordChars = passwordInput.getPassword();
        String enteredPassword = new String(enteredPasswordChars);
        String username = "username";
        String password = "password";
        try {
                FileReader fr = new FileReader("src\\main\\java\\com\\mycompany\\fpt\\HDD\\userInfo.txt");
                BufferedReader br = new BufferedReader(fr);
                username = br.readLine();
                password = br.readLine();
            } catch (IOException q) {
                out.println("file not found");
            }

        enteredUsername = enteredUsername.toLowerCase();
        if (username.equals(enteredUsername) && password.equals(enteredPassword)) {
            // Open main window on sucessful login
                Main x = new Main();
                x.setSize(800, 450);
                x.setVisible(true);
                dispose();
            } else {
                // Display an error message
                JOptionPane.showMessageDialog(this, "Invalid username or password. Please try again.", "Login Error", JOptionPane.ERROR_MESSAGE);
            }

            // Clear the password field for security
            passwordInput.setText("");
        
        
    }//GEN-LAST:event_EnterActionPerformed

    private void powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerActionPerformed
        int reply = JOptionPane.showConfirmDialog(this, "Are you sure you want to shut down the computer?", getTitle(), JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_powerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Start start = new Start();
                start.setSize(800, 450);
                start.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enter;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Username;
    private javax.swing.JPanel background;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JButton power;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
private void hideLogoAfterDelay() {
    // display bootup screen for 3.5 seconds
        Timer timer = new Timer(3500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                logo.setVisible(false);
                power.setVisible(true);
            }
        });
        timer.setRepeats(false);
        timer.start();
    }

}
